### ISSUE TITLE
Kanban board review

### ISSUE THREAD

**Issue by AkshithaReddy1899** [AkshithaReddy1899/JS-Capstone#21]
Hello,  we are a team of two people @AkshithaReddy1899 , @OybekKayumov . 

Here's a link for our kanban board

[Kanban board](https://github.com/users/AkshithaReddy1899/projects/1)

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
### according to the below requirement in groups with 2 students the cards which mention Student C should be removed.
- [ ] If your group includes two people - remove all cards with Student C in the title.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by uwadonat** [comment]
Hi **@Team**, 

Your project is complete!   
Congratulations! 🎉 

![approved](https://user-images.githubusercontent.com/65860678/151808109-843b5ca2-ba10-40dc-846f-cdbdd60c78eb.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by OybekKayumov** [comment]
Thank you!
